version: 0.2

# env:
#   variables:
#     NODE_HEADERS_URL: "http://nodejs.org/dist/v18.17.1"

phases:
  # install:
  #   commands:
  #     - npm install
  build:
    commands:
      - cd wasm;
      - mkdir build
      - cd build
      - cmake -DCMAKE_TOOLCHAIN_FILE="/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" -DBUILD_TYPE=wasm -DCOMMIT_HASH=${CI_COMMIT_SHORT_SHA} .. || exit 1
      - make || exit 1
  # post_build:
  #   commands:
  #     - npm pack